#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="$basedir/D:/Gre/toC/graduation-design/node_modules/.store/marked@12.0.1/node_modules"
else
  export NODE_PATH="$NODE_PATH:$basedir/D:/Gre/toC/graduation-design/node_modules/.store/marked@12.0.1/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../.store/marked@12.0.1/node_modules/marked/bin/marked.js" "$@"
else
  exec node  "$basedir/../.store/marked@12.0.1/node_modules/marked/bin/marked.js" "$@"
fi
